import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { Header } from '@widgets/header'

import './globals.css'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['cyrillic', 'latin'],
})

export const metadata: Metadata = {
  title: 'Hope&dessert',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${nunito.variable}  antialiased`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
